import { Metadata } from 'next';
import Link from 'next/link';
import JsonLd from '@/components/JsonLd';
import { generateBreadcrumbSchema, SUPPORT_EMAIL } from '@/lib/seo';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'TypeGone Terms of Service — the rules and conditions governing your use of TypeGone voice-to-text services across Telegram, desktop, and web.',
  alternates: { canonical: 'https://typegone.com/terms' },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <>
      <JsonLd data={generateBreadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Terms of Service', url: '/terms' }])} />

      <section className="max-w-3xl mx-auto px-6 pt-32 pb-24">
        <nav className="flex items-center gap-2 text-xs text-text-dim mb-8">
          <Link href="/" className="hover:text-text-muted transition-colors">Home</Link>
          <span>/</span>
          <span className="text-text-muted">Terms of Service</span>
        </nav>

        <h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight mb-4">Terms of Service</h1>
        <p className="text-text-dim text-sm mb-12">Last Updated: February 14, 2026</p>

        <div className="prose-tg">
          <p>
            Welcome to TypeGone! TypeGone provides software and services, including the TypeGone Telegram bot, desktop application, and web platform, to help users convert voice into polished, formatted text using artificial intelligence (collectively, the &quot;Services&quot;). These Terms of Service (&quot;Terms&quot;) are entered into by TypeGone and the individual or entity accepting these Terms (&quot;Customer,&quot; &quot;you,&quot; or &quot;your&quot;) and govern your access to and use of the Services. By using the Services, you agree to these Terms and our <Link href="/privacy">Privacy Policy</Link>, which explains how we collect and use your information.
          </p>
          <p>
            To use the Services, you must be at least 13 years old if you reside in the United States, or at least 16 years old if you reside elsewhere. If you are under 18 years old, depending on where you reside, you may need to obtain consent from your parents or guardians, and they may need to enter into these Terms on your behalf.
          </p>

          <h2>1. Your Account</h2>
          <p>
            Certain features of the Services require an account. When using the Telegram bot, your Telegram user ID serves as your account identifier. When using the desktop application or web platform, you may create an account with an email address. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. Do not share your credentials or allow others to access your account. If you know or suspect that your account has been compromised, notify us immediately at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
          </p>

          <h2>2. Your Content</h2>
          <p>
            <strong>A. Ownership.</strong> All of your content remains yours. TypeGone does not claim ownership of any voice recordings you submit (&quot;Input&quot;) or the text generated by the Services (&quot;Output&quot;). Together, your Input and Output are referred to as &quot;Customer Content.&quot; As between you and TypeGone, to the extent permitted by applicable law, you retain all ownership of Input and you own all Output.
          </p>
          <p>
            <strong>B. License to provide Services.</strong> By submitting voice recordings and other content to the Services, you grant TypeGone a worldwide, non-exclusive, royalty-free license to access, process, and transmit your content solely for the purpose of providing, maintaining, and improving the Services. This processing occurs in real time and content is immediately discarded upon delivery, as described in our <Link href="/data-privacy">Data Ownership &amp; Privacy</Link> page.
          </p>
          <p>
            <strong>C. AI output disclaimer.</strong> THE SERVICES USE LARGE LANGUAGE MODELS AND OTHER AI CAPABILITIES TO GENERATE OUTPUT. TYPEGONE MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, OR SUITABILITY OF ANY OUTPUT. YOU SHOULD NOT RELY ON ANY OUTPUT WITHOUT INDEPENDENTLY VERIFYING ITS ACCURACY. OUTPUT MAY CONTAIN INACCURACIES EVEN WHEN IT APPEARS DETAILED OR SPECIFIC.
          </p>
          <p>
            <strong>D. Third-party output.</strong> Due to the nature of generative AI, Output generated for other users based on their voice input may be similar or identical to Output generated for you. You acknowledge that such third-party output is not your content and you have no rights to it.
          </p>
          <p>
            <strong>E. Data controls.</strong> You can control whether feedback you voluntarily submit may be used for improving TypeGone&apos;s services. For details, see our <Link href="/data-privacy">Data Ownership &amp; Privacy</Link> page.
          </p>

          <h2>3. Acceptable Use</h2>
          <p>
            <strong>A. General restrictions.</strong> You may only use the Services to the extent permitted by applicable law. You agree not to:
          </p>
          <ul>
            <li>Record or transcribe others&apos; speech without their consent</li>
            <li>Violate or circumvent any security or authentication measures of the Services</li>
            <li>Disassemble, decompile, or reverse-engineer any part of the Services to access source code, algorithms, or other TypeGone intellectual property</li>
            <li>Interfere with or disrupt the Services or their infrastructure, including by sending viruses, overloading, flooding, or spamming</li>
            <li>Access, search, or create Service accounts through any means other than publicly supported interfaces</li>
            <li>Post, share, or process content that is illegal, harmful, threatening, abusive, defamatory, or that infringes on others&apos; intellectual property or privacy rights</li>
            <li>Engage in any form of payment fraud, including unauthorized use of payment methods or abuse of free credits</li>
            <li>Sell, resell, or redistribute the Services unless specifically authorized</li>
          </ul>
          <p>
            <strong>B. AI feature restrictions.</strong> You will not and will not allow any other person to:
          </p>
          <ul>
            <li>Use AI features or any Output to infringe any third-party rights</li>
            <li>Use AI features or any Output to develop, train, or improve any other AI or machine learning model</li>
            <li>Claim that any Output has been reviewed, approved, or endorsed by TypeGone</li>
            <li>Use AI features for automated decision-making that has legal or similarly significant impact on individuals without adequate human oversight</li>
            <li>Use AI features for discriminatory, harassing, harmful, or unethical purposes</li>
          </ul>
          <p>
            <strong>C. Violations.</strong> TypeGone reserves the right to take appropriate action against conduct that violates these Terms, which may include removing or disabling access to content, suspending your access, or terminating your account.
          </p>

          <h2>4. The Services</h2>
          <p>
            Subject to your compliance with these Terms and payment of applicable fees, TypeGone grants you a revocable, non-exclusive, non-transferable, non-sublicensable limited right to access and use the Services. The Services may allow you to download client software, including the TypeGone desktop application, which may update automatically. As long as you comply with these Terms, we grant you a limited right to use such Software solely for accessing the Services. If any component of the Software is offered under an open-source license, the provisions of that license may expressly override portions of these Terms.
          </p>

          <h2>5. Beta Services</h2>
          <p>
            TypeGone may release products and features that are still being tested (&quot;Beta Services&quot;), such as the TypeGone desktop application. Beta Services are identified with &quot;beta,&quot; &quot;preview,&quot; or similar labels and may not be as reliable as our other services. Beta Services are provided to gather user feedback, and by using them you agree that we may contact you to collect such feedback.
          </p>

          <h2>6. Paid Services &amp; Credits</h2>
          <p>
            <strong>A. Credit system.</strong> TypeGone operates on a credit-based system. You purchase message credits that are consumed each time you process a voice recording. Credits do not expire. New users receive 3 free messages with no signup required.
          </p>
          <p>
            <strong>B. Payment methods.</strong> Payments are processed through Telegram Stars (handled by Telegram) and USDT cryptocurrency on the TRC20 network. We do not collect or store credit card numbers or bank details directly. All payment processing is subject to the terms of the applicable payment processor.
          </p>
          <p>
            <strong>C. Refunds.</strong> All sales are final. Refunds are issued only where required by applicable law.
          </p>
          <p>
            <strong>D. Pricing changes.</strong> We may change pricing at any time with reasonable notice. Existing purchased credits are not affected by price changes.
          </p>
          <p>
            <strong>E. Free tier and referrals.</strong> Free credits cannot be transferred, sold, or exchanged. TypeGone may offer a referral program where you earn bonus credits for inviting new users. Abuse of the referral system (creating fake accounts, self-referrals) will result in account termination and forfeiture of all credits.
          </p>

          <h2>7. Third-Party Services</h2>
          <p>
            The Services operate with third-party services, including large language model providers (such as OpenAI), to deliver transcription and text formatting. Data sent to these providers is configured for zero data retention — your voice data and text are processed and immediately discarded by these providers. Your data is never used to train these services. TypeGone is not responsible for the operation, availability, or terms of any third-party services.
          </p>

          <h2>8. TypeGone&apos;s Intellectual Property</h2>
          <p>
            The Services (including the TypeGone name, logo, website, software, and design) are owned by TypeGone and protected by copyright, trade secrets, trademarks, and other applicable laws. These Terms do not grant you any rights, title, or interest in our intellectual property beyond the limited right to use the Services. We welcome feedback about the Services, but please note that we may use feedback without any obligation to you, even after termination of these Terms.
          </p>

          <h2>9. Our Rights</h2>
          <p>
            TypeGone may, at any time in our sole discretion and without liability (unless prohibited by applicable law): (a) change the Services and their functionality; (b) suspend or discontinue the Services; (c) terminate, suspend, or restrict your access; (d) change eligibility criteria. If we discontinue the Services before the end of a period for which you have paid, we will refund the unused portion of prepaid fees.
          </p>

          <h2>10. Privacy</h2>
          <p>
            By using the Services, you acknowledge that you have read and understand our <Link href="/privacy">Privacy Policy</Link> and <Link href="/data-privacy">Data Ownership &amp; Privacy</Link> page, which describe how we handle your personal information and voice data.
          </p>

          <h2>11. Disclaimer of Warranties</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TYPEGONE MAKES NO WARRANTIES REGARDING THE SERVICES, WHETHER EXPRESS OR IMPLIED. THE SERVICES, INCLUDING ALL OUTPUT, ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; TYPEGONE DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT OUTPUT WILL BE ACCURATE OR COMPLETE.
          </p>
          <p>
            Some jurisdictions do not allow the exclusion of certain warranties, so the above may not apply to you in full. You may have additional statutory rights that cannot be waived.
          </p>

          <h2>12. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, TYPEGONE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUES, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES ARISING FROM: (A) YOUR USE OF OR INABILITY TO USE THE SERVICES OR ANY OUTPUT; (B) ANY CONDUCT OR CONTENT OF THIRD PARTIES ON THE SERVICES; (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR CONTENT. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
          </p>
          <p>
            IF YOU ARE A RESIDENT OF THE EUROPEAN UNION OR EUROPEAN ECONOMIC AREA, TYPEGONE IS LIABLE UNDER STATUTORY PROVISIONS FOR INTENTIONAL AND GROSS NEGLIGENCE BY TYPEGONE, OUR LEGAL REPRESENTATIVES, DIRECTORS, OR OTHER AGENTS.
          </p>

          <h2>13. Indemnification</h2>
          <p>
            To the maximum extent permitted by law, you agree to indemnify and hold harmless TypeGone and its officers, directors, employees, and agents from and against all damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising from: (a) your breach of these Terms; (b) your Customer Content; (c) your violation of any applicable law. Your indemnification obligations do not apply to the extent directly caused by TypeGone&apos;s breach of these Terms, or, if you are an EU user, to the extent consequences are not reasonably foreseeable.
          </p>

          <h2>14. Termination</h2>
          <p>
            You may stop using the Services at any time. If TypeGone reasonably believes you have violated these Terms, your use creates risk or harm to us or others, or you have no Paid Services and have not accessed the Services for twelve (12) consecutive months, we may suspend or terminate your access with notice. Upon termination, your right to use the Services ceases immediately. Purchased credits that have not been used are non-refundable unless required by law. All provisions that by their nature should survive termination shall survive, including ownership, disclaimers, indemnity, and limitations of liability.
          </p>

          <h2>15. Dispute Resolution</h2>
          <p>
            <strong>A. Informal resolution.</strong> Before bringing a formal claim, you agree to first attempt to resolve the dispute by emailing <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with a description of your claim. We will attempt to resolve the dispute informally within sixty (60) days.
          </p>
          <p>
            <strong>B. Governing law.</strong> These Terms will be governed by the laws of the jurisdiction in which TypeGone operates. Consumers in certain jurisdictions, including the European Union, may have additional rights under local law that cannot be overridden by these Terms.
          </p>

          <h2>16. Modifications</h2>
          <p>
            We may update these Terms from time to time. Material changes will be communicated through the Services. The notice will specify a reasonable period after which the updated terms take effect. Modifications will not apply retroactively. Continued use after changes take effect constitutes acceptance. If you disagree, you should stop using the Services.
          </p>

          <h2>17. General</h2>
          <p>
            These Terms constitute the complete agreement between you and TypeGone. TypeGone&apos;s failure to enforce a provision does not waive its right to do so later. If any provision is found unenforceable, the remaining provisions remain in full force. You may not assign your rights under these Terms; TypeGone may assign its rights to any affiliate, subsidiary, or successor in interest.
          </p>

          <h2>18. Contact</h2>
          <p>
            Questions about these Terms? Contact us at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
          </p>
        </div>
      </section>
    </>
  );
}
